### ISSUE TITLE
No left room message

### ISSUE THREAD

**Issue by molinto** [justadudewhohacks/websocket-chat#1]
Hi, just came across your medium article & code. Great job btw!!

Little thing really, when you select a user, join a room & then click on a the user profile icon (main image on the left). The event.message doesn't report this as the user has left the room.  Whereas you can can rejoin the same room & it says:

```
Daryl joined Terminus
Daryl joined Terminus
Daryl joined Terminus
Daryl joined Terminus
```

**Comment by justadudewhohacks** [comment]
Hi, thanks a lot for your feedback. This is just a toy example, to illustrate the point, so it's not perfect. Nevertheless thanks for reporting this :)

**Comment by molinto** [comment]
No worries, just some feedback.

Thanks again for putting this together :)
